version: '3.8'
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '${HTTP_PORT}:80' # Public HTTP Port
      - '${HTTPS_PORT}:443' # Public HTTPS Port
      - '${ADMIN_PORT}:81' # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - default
      - frontend-network

networks:
  default:
  frontend-network:
    external: true
    name: ${FRONTEND_NETWORK}
